# Generated by Django 4.2.7 on 2023-11-02 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_options_alter_news_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 20, 38, 13, 405063)),
        ),
    ]
