# Generated by Django 4.2.7 on 2023-11-02 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_news_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 21, 40, 41, 800424)),
        ),
    ]
