# Generated by Django 4.2.7 on 2023-11-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_update_at'),
        ('profile_', '0002_profile_news_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newss', to='news.news'),
        ),
    ]
